sources:
    - name: he_db
      schema: warehouse
      tables: 
        - name: stg_data_ads
          identifier: data_field_job_ads
        - name: stg_data_ads_must
          identifier: data_field_job_ads__must_have__work_experiences
      
    