USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS he_db;

CREATE WAREHOUSE IF NOT EXISTS he_wh
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for development and analysis of higher education data';

USE WAREHOUSE he_wh;
USE DATABASE he_db;

CREATE SCHEMA IF NOT EXISTS staging;

CREATE SCHEMA IF NOT EXISTS warehouse;

CREATE SCHEMA IF NOT EXISTS mart;
SHOW SCHEMAS;