models:
  - name: dim_employer
    description: "Information about the employer with name, workplace, address, region and such."
    columns:
      - name: employer_id
        data_tests:
          - unique
        

      - name: workplace_city
        data_tests:
          - not_null
      - name: employer_workplace
          - not_null
        data_tests:
          - not_null
        
  - name: dim_date
    description: "Information about the application deadline, publication date and last publication date."
    columns:
      - name: application_deadline
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: datetime
          - not_null
      - name: publication_date
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: datetime
          - not_null
      - name: last_publication_date
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: datetime
          - not_null

      - name: workplace_city
        data_tests:
          - not_null

        
  - name: dim_job_details
    description: "Information about the ads like headline, description salary type ect."
    columns:
      - name: job_details_id
        data_tests:
          - not_null
          - unique
      - name: headline
        data_tests:
          - not_null

        

  - name: fct_job_ads
    description: "Information about relevance and vacancies, also bridge to dimensions"
    columns:
      - name: job_details_key
        data_tests:
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
      - name: relevance
        description: "How relevant the search is to the ad"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 1 

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: vacancies
        description: "How many vacencies does the Employer have for that ad"
        data_tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
            

          